package com.ails.stirdatabackend.model;

public enum LogActionType {
    READ_REGISTRY_DCAT,
    READ_NACE_DCAT,
    READ_DATASET_METADATA,
    QUERY_DATASET_PROPERTIES,
    QUERY_NACE_PROPERTIES,
    QUERY_NUTS_PROPERTIES,
    QUERY_COMPANY_TYPE_PROPERTIES,
    COMPUTE_DATA_STATISTICS,
    COMPUTE_NUTS_STATISTICS,
    COMPUTE_NACE_STATISTICS,
    COMPUTE_FOUNDING_STATISTICS,
    COMPUTE_DISSOLUTION_STATISTICS,
    COMPUTE_NUTS_NACE_STATISTICS,
    COMPUTE_NUTS_FOUNDING_STATISTICS,
    COMPUTE_NUTS_DISSOLUTION_STATISTICS,
    COMPUTE_NACE_FOUNDING_STATISTICS,
    COMPUTE_NACE_DISSOLUTION_STATISTICS,
    
    RELOAD_COUNTRY,
    
    
}
